# Add this layer to BBPATH and make its recipes visible to BitBake.
BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "jamesc"
BBFILE_PATTERN_jamesc = "^${LAYERDIR}/"
BBFILE_PRIORITY_jamesc = "6"

LAYERSERIES_COMPAT_jamesc = "scarthgap"
LAYERDEPENDS_jamesc = "core raspberrypi rauc"
